server:
  port: 8080
spring:
  application:
    name: game
  datasource:
    url: localhost
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true